### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by albosta** [smsalah/hr_pyzk#4]
Odoo Server Error
Traceback (most recent call last):
  File "/odoo-dev/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo-dev/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo-dev/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo-dev/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo-dev/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 797, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 844, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hr_pyzk failed: file hr_pyzk/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_device_users' in field 'Object'
No matching record found for external id 'model_devices' in field 'Object'
No matching record found for external id 'model_device_attendances' in field 'Object'
No matching record found for external id 'model_combined_attendances' in field 'Object'
No matching record found for external id 'model_user_wizard' in field 'Object'
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)

**Comment by albosta** [comment]
Downloaded from github again and getting this error:
Odoo Server Error
Traceback (most recent call last):
  File "/odoo-dev/odoo/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 1059, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Model not found: device.users

Error context:
View `device_users_tree_view`
[view_id: 424, xml_id: n/a, model: device.users, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo-dev/odoo/odoo/models.py", line 3805, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo-dev/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo-dev/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo-dev/odoo/odoo/models.py", line 3542, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo-dev/odoo/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo-dev/odoo/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/odoo-dev/odoo/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/odoo-dev/odoo/odoo/models.py", line 1106, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nModel not found: device.users\n\nError context:\nView `device_users_tree_view`\n[view_id: 424, xml_id: n/a, model: device.users, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo-dev/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo-dev/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo-dev/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo-dev/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo-dev/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo-dev/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/odoo-dev/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo-dev/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo-dev/odoo/odoo/models.py", line 3805, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo-dev/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo-dev/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo-dev/odoo/odoo/models.py", line 3542, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo-dev/odoo/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo-dev/odoo/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo-dev/odoo/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/odoo-dev/odoo/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/odoo-dev/odoo/odoo/models.py", line 1106, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Model not found: device.users

Error context:
View `device_users_tree_view`
[view_id: 424, xml_id: n/a, model: device.users, parent_id: n/a]
None" while parsing /odoo-dev/custom/addons/hr_pyzk/views/device_users_view.xml:2, near
<record id="device_users_tree_view" model="ir.ui.view">
            <field name="name">device_users_tree_view</field>
            <field name="model">device.users</field>
            <field name="arch" type="xml">
                <tree string="Device Users Tree View">
                   
                    <field name="device_user_id"/>
                    <field name="name"/>
                    <field name="employee_id"/>
                </tree>
            </field>
        </record>

**Comment by albosta** [comment]
This was a python 3.5 issue, I upgraded pyzk from .6 to ,9 and it was resolved.

Currently I'm facing an issue with pulling the time:

Odoo Server Error
Traceback (most recent call last):
  File "/odoo-dev/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo-dev/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo-dev/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo-dev/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo-dev/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo-dev/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo-dev/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo-dev/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo-dev/odoo/addons/hr_pyzk/wizard/user_wizard.py", line 61, in import_attendance
    for x in attendances for y in device_users if
  File "/odoo-dev/odoo/addons/hr_pyzk/wizard/user_wizard.py", line 62, in <listcomp>
    int(x[0]) == y.device_user_id and x[2] <= 1]
ValueError: astimezone() cannot be applied to a naive datetime
